# This workflow will run tests to ensure HydroGenerate is working

name: Test HydroGenerate

on:
  push:
    branches: 
      - main
      - jugc-pytest
  pull_request:
    branches: 
      - main
      - jugc-pytest

jobs:
  build:
    runs-on: ubuntu-latest
    python-version: 3.8

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          conda env create -f hat_env.yml

      - name: Test with pytest and report coverage
        run: |
          cd tests
          coverage run -m pytest
          coverage report -m
          cd ..

